# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations

from enum import StrEnum

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    PositiveInt,
    confloat,
    conint,
    constr,
)


class CardBrand(StrEnum):
    """
    Card brand from the Stripe payment method
    """

    visa = 'visa'
    mastercard = 'mastercard'
    amex = 'amex'
    discover = 'discover'
    jcb = 'jcb'
    diners = 'diners'
    unionpay = 'unionpay'
    unknown = 'unknown'


class PaymentFailedEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    stripeId: constr(min_length=1) = Field(
        ..., description='Stripe event or invoice item id, e.g. evt_...'
    )
    customerId: constr(min_length=1) = Field(
        ..., description='Stripe customer id, e.g. cus_...'
    )
    amountMinor: PositiveInt = Field(
        ..., description='Amount in minor units (cents), e.g. 4900 = $49.00'
    )
    currency: constr(pattern=r'^[a-z]{3}$') = Field(
        ..., description='ISO 4217 currency code (lowercase)'
    )
    declineCode: constr(min_length=1) = Field(
        ..., description='Stripe decline code, e.g. "insufficient_funds"'
    )
    attempt: conint(ge=1) = Field(
        ..., description='1-based retry attempt number for this invoice'
    )
    cardBrand: CardBrand = Field(
        ..., description='Card brand from the Stripe payment method'
    )
    ts: AwareDatetime = Field(
        ..., description='Failure timestamp, RFC 3339 with offset'
    )


class Action(StrEnum):
    RETRY = 'RETRY'
    SUPPRESS = 'SUPPRESS'
    ASK_CUSTOMER = 'ASK_CUSTOMER'


class ShapTopItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    feature: constr(min_length=1)
    contribution: float = Field(
        ..., description='SHAP value: signed contribution to P(recover) log-odds'
    )


class Decision(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    paymentId: constr(min_length=1) = Field(
        ..., description='Internal id of the failed payment this decision covers'
    )
    action: Action
    scheduledFor: AwareDatetime | None = Field(
        None, description='Planned retry moment; required iff action === RETRY'
    )
    pRecover: confloat(ge=0.0, le=1.0) = Field(
        ..., description='Model-estimated probability of recovery'
    )
    shapTop: list[ShapTopItem] = Field(
        ...,
        description='Top-5 SHAP feature contributions for the explanation panel',
        max_length=5,
    )
    ruleHits: list[constr(min_length=1)] = Field(
        ...,
        description='Compliance rule citations that fired, e.g. "VISA-CAT1-NEVER-RETRY"',
    )
    modelVersion: constr(min_length=1) = Field(
        ..., description='Versioned model artifact id, e.g. "propensity-v0.1.0"'
    )


class Actor(StrEnum):
    MODEL = 'MODEL'
    RULE = 'RULE'
    HUMAN = 'HUMAN'


class AuditEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    seq: conint(ge=0) = Field(
        ...,
        description='Application-assigned monotonically increasing sequence number (0 = genesis)',
    )
    prevHash: constr(pattern=r'^[0-9a-f]{64}$') = Field(
        ...,
        description='Hash of the previous entry; all-zero hex for the genesis entry',
    )
    hash: constr(pattern=r'^[0-9a-f]{64}$') = Field(
        ...,
        description='SHA-256 over (seq, prevHash, decisionRef, actor, ts) — tamper-evident',
    )
    decisionRef: constr(min_length=1) = Field(
        ..., description='Id of the Decision this entry attests'
    )
    actor: Actor
    ts: AwareDatetime


class Kind(StrEnum):
    PAYMENT_FAILED = 'PAYMENT_FAILED'
    PAYMENT_RECOVERED = 'PAYMENT_RECOVERED'
    CARD_UPDATED = 'CARD_UPDATED'


class Source(StrEnum):
    """
    Provenance: real Stripe test-mode capture or clearly-labeled synthetic seed
    """

    stripe_test_capture = 'stripe-test-capture'
    synthetic_seed = 'synthetic-seed'


class PaymentFailed(BaseModel):
    """
    Present iff kind === PAYMENT_FAILED
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    stripeId: constr(min_length=1) = Field(
        ..., description='Stripe event or invoice item id, e.g. evt_...'
    )
    customerId: constr(min_length=1) = Field(
        ..., description='Stripe customer id, e.g. cus_...'
    )
    amountMinor: PositiveInt = Field(
        ..., description='Amount in minor units (cents), e.g. 4900 = $49.00'
    )
    currency: constr(pattern=r'^[a-z]{3}$') = Field(
        ..., description='ISO 4217 currency code (lowercase)'
    )
    declineCode: constr(min_length=1) = Field(
        ..., description='Stripe decline code, e.g. "insufficient_funds"'
    )
    attempt: conint(ge=1) = Field(
        ..., description='1-based retry attempt number for this invoice'
    )
    cardBrand: CardBrand = Field(
        ..., description='Card brand from the Stripe payment method'
    )
    ts: AwareDatetime = Field(
        ..., description='Failure timestamp, RFC 3339 with offset'
    )


class ReplayEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    eventId: constr(min_length=1) = Field(
        ..., description='Dedupable id, stable across replay runs'
    )
    kind: Kind
    source: Source = Field(
        ...,
        description='Provenance: real Stripe test-mode capture or clearly-labeled synthetic seed',
    )
    capturedAt: AwareDatetime = Field(
        ..., description='Original capture time (RFC 3339)'
    )
    paymentFailed: PaymentFailed | None = Field(
        None, description='Present iff kind === PAYMENT_FAILED'
    )
